SELECT
    TO_CHAR(DATE_TRUNC('month', APP_DATE), 'YYYY-MM') AS PERIOD,
    CREDIT_TIER,
    COUNT(*) AS APPLICATION_COUNT
FROM APPLICATION_EVENTS
WHERE DEALER_ID = ?
    AND APP_DATE IS NOT NULL
    AND CREDIT_TIER IS NOT NULL
GROUP BY PERIOD, CREDIT_TIER
ORDER BY PERIOD, CREDIT_TIER
