SELECT
    m.DEALER_ID,
    m.DEALER_NAME,
    m.TIER,
    m.TERRITORY,
    m.LATITUDE,
    m.LONGITUDE,
    TO_CHAR(p.PERIOD, 'YYYY-MM-DD') AS PERIOD,
    p.LOOK_TO_BOOK,
    p.FUNDING_VELOCITY,
    p.EXCEPTION_RATE
FROM DEALER_MASTER m
JOIN DEALER_PERFORMANCE p
    ON p.DEALER_ID = m.DEALER_ID
ORDER BY m.DEALER_ID, p.PERIOD
