WITH dealer_tier AS (
    SELECT TIER FROM DEALER_MASTER WHERE DEALER_ID = ?
)
SELECT
    (SELECT TIER FROM dealer_tier) AS TIER,
    AVG(CASE WHEN a.CREDIT_TIER = 'Prime' THEN 1.0 ELSE 0 END) AS PRIME,
    AVG(CASE WHEN a.CREDIT_TIER = 'Near_Prime' THEN 1.0 ELSE 0 END) AS NEAR_PRIME,
    AVG(CASE WHEN a.CREDIT_TIER = 'Subprime' THEN 1.0 ELSE 0 END) AS SUBPRIME
FROM APPLICATION_EVENTS a
JOIN DEALER_MASTER m ON m.DEALER_ID = a.DEALER_ID
WHERE m.TIER = (SELECT TIER FROM dealer_tier)
    AND a.DEALER_ID <> ?
    AND a.CREDIT_TIER IS NOT NULL
