USE ROLE ACCOUNTADMIN;

SHOW USERS LIKE 'HOL_USER_%';
SELECT
    "name" AS username,
    "default_role",
    "default_warehouse",
    "disabled",
    "mins_to_bypass_mfa"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
ORDER BY username;

SELECT COUNT(*) AS user_count FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW ROLES LIKE 'HOL_ROLE_%';
SELECT COUNT(*) AS role_count FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS TO ROLE HOL_ROLE_01;

SELECT 'DEALER_MASTER' AS table_name, COUNT(*) AS row_count FROM HOL_DEALER360_MASTER.CORE.DEALER_MASTER
UNION ALL
SELECT 'APPLICATION_EVENTS', COUNT(*) FROM HOL_DEALER360_MASTER.CORE.APPLICATION_EVENTS
UNION ALL
SELECT 'DEALER_PERFORMANCE', COUNT(*) FROM HOL_DEALER360_MASTER.CORE.DEALER_PERFORMANCE
UNION ALL
SELECT 'FUNDING_EVENTS', COUNT(*) FROM HOL_DEALER360_MASTER.CORE.FUNDING_EVENTS
UNION ALL
SELECT 'SERVICING_EVENTS', COUNT(*) FROM HOL_DEALER360_MASTER.CORE.SERVICING_EVENTS;

SHOW GIT REPOSITORIES LIKE 'HOL_GIT_REPO';
LIST @HOL_DEALER360_MASTER.CORE.HOL_GIT_REPO/branches/main/dealer_360_seed_data/;

SHOW DATABASES LIKE 'HOL_DEALER360_%';
SELECT "name" AS db_name, "created_on"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" != 'HOL_DEALER360_MASTER'
ORDER BY db_name;

SELECT COUNT(*) AS clone_count
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SELECT database_name, database_id, clone_group_id, created
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES
WHERE database_name ILIKE 'HOL_DEALER360%'
  AND deleted IS NULL
ORDER BY database_name;

SELECT 'DEALER_MASTER' AS table_name, COUNT(*) AS row_count FROM HOL_DEALER360_01.CORE.DEALER_MASTER
UNION ALL
SELECT 'APPLICATION_EVENTS', COUNT(*) FROM HOL_DEALER360_01.CORE.APPLICATION_EVENTS
UNION ALL
SELECT 'FUNDING_EVENTS', COUNT(*) FROM HOL_DEALER360_01.CORE.FUNDING_EVENTS
UNION ALL
SELECT 'SERVICING_EVENTS', COUNT(*) FROM HOL_DEALER360_01.CORE.SERVICING_EVENTS
UNION ALL
SELECT 'DEALER_PERFORMANCE', COUNT(*) FROM HOL_DEALER360_01.CORE.DEALER_PERFORMANCE;

USE ROLE SYSADMIN;
USE ROLE HOL_ROLE_01;

SHOW DATABASES LIKE 'HOL_DEALER360_%';

SELECT COUNT(*) FROM HOL_DEALER360_01.CORE.DEALER_MASTER;

SELECT COUNT(*) FROM HOL_DEALER360_02.CORE.DEALER_MASTER;

USE ROLE ACCOUNTADMIN;
