WITH dealer_tier AS (
    SELECT TIER FROM DEALER_MASTER WHERE DEALER_ID = ?
)
SELECT
    (SELECT TIER FROM dealer_tier) AS TIER,
    AVG(CASE WHEN f.DEALER_ID = ? AND f.EXCEPTION_FLAG THEN 1.0
             WHEN f.DEALER_ID = ? THEN 0.0 END) AS DEALER_RATE,
    AVG(CASE WHEN f.DEALER_ID <> ? AND f.EXCEPTION_FLAG THEN 1.0
             WHEN f.DEALER_ID <> ? THEN 0.0 END) AS PEER_RATE
FROM FUNDING_EVENTS f
JOIN DEALER_MASTER m ON m.DEALER_ID = f.DEALER_ID
WHERE m.TIER = (SELECT TIER FROM dealer_tier)
