WITH dealer_tier AS (
    SELECT TIER FROM DEALER_MASTER WHERE DEALER_ID = ?
)
SELECT
    (SELECT TIER FROM dealer_tier) AS TIER,
    AVG(DATEDIFF('day', f.CONTRACT_DATE, f.FUNDED_DATE)) AS AVG_FUNDING_DAYS
FROM FUNDING_EVENTS f
JOIN DEALER_MASTER m ON m.DEALER_ID = f.DEALER_ID
WHERE m.TIER = (SELECT TIER FROM dealer_tier)
    AND f.DEALER_ID <> ?
    AND f.CONTRACT_DATE IS NOT NULL
    AND f.FUNDED_DATE IS NOT NULL
