WITH dealer_tier AS (
    SELECT TIER FROM DEALER_MASTER WHERE DEALER_ID = ?
)
SELECT
    (SELECT TIER FROM dealer_tier) AS TIER,
    AVG(CASE WHEN s.EPD_FLAG THEN 1.0 ELSE 0 END) AS PEER_EPD_RATE
FROM SERVICING_EVENTS s
JOIN DEALER_MASTER m ON m.DEALER_ID = s.DEALER_ID
WHERE m.TIER = (SELECT TIER FROM dealer_tier)
    AND s.DEALER_ID <> ?
