SELECT
    EXCEPTION_TYPE,
    COUNT(*) AS EXCEPTION_COUNT
FROM FUNDING_EVENTS
WHERE DEALER_ID = ?
    AND EXCEPTION_FLAG = TRUE
    AND EXCEPTION_TYPE IS NOT NULL
    AND EXCEPTION_TYPE <> 'None'
GROUP BY EXCEPTION_TYPE
ORDER BY EXCEPTION_COUNT DESC
