SELECT
    TO_CHAR(DATE_TRUNC('month', CONTRACT_DATE), 'YYYY-MM') AS PERIOD,
    COUNT(*) AS CONTRACT_COUNT,
    AVG(DATEDIFF('day', CONTRACT_DATE, FUNDED_DATE)) AS AVG_FUNDING_DAYS,
    AVG(CASE WHEN DATEDIFF('day', CONTRACT_DATE, FUNDED_DATE) > 5 THEN 1 ELSE 0 END) AS SLOW_SHARE
FROM FUNDING_EVENTS
WHERE DEALER_ID = ?
    AND CONTRACT_DATE IS NOT NULL
    AND FUNDED_DATE IS NOT NULL
GROUP BY PERIOD
ORDER BY PERIOD
