SELECT
    COUNT(*) AS LOAN_COUNT,
    AVG(CASE WHEN EPD_FLAG THEN 1 ELSE 0 END) AS EPD_RATE,
    SUM(CASE WHEN DPD_STATUS = 'Current' THEN 1 ELSE 0 END) AS DPD_CURRENT,
    SUM(CASE WHEN DPD_STATUS = '30' THEN 1 ELSE 0 END) AS DPD_30,
    SUM(CASE WHEN DPD_STATUS = '60' THEN 1 ELSE 0 END) AS DPD_60,
    SUM(CASE WHEN DPD_STATUS = '90+' THEN 1 ELSE 0 END) AS DPD_90_PLUS
FROM SERVICING_EVENTS
WHERE DEALER_ID = ?
