-- SECTION 3: The Template Database, named COCO_SDLC_HOL_DEALER_MASTER

USE ROLE ATTENDEE_ROLE;

CREATE DATABASE IF NOT EXISTS COCO_SDLC_HOL_DEALER_MASTER
    COMMENT = 'Dealer 360 HOL lab template — hydrated from git seed data, cloned per attendee';

USE DATABASE COCO_SDLC_HOL_DEALER_MASTER;
CREATE SCHEMA IF NOT EXISTS CORE;
USE SCHEMA CORE;
